# Generated by Django 2.2.6 on 2019-12-06 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0018_auto_20191206_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EveryProductsOnMainList', models.ManyToManyField(related_name='Products', to='Products.ProductImage')),
                ('LeftBarProduct', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.ProductImage')),
            ],
            options={
                'verbose_name': 'MainList Product',
                'verbose_name_plural': 'MainList Products',
            },
        ),
    ]
