# Generated by Django 2.2.6 on 2019-12-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainlist',
            name='EveryProductsOnMainList',
            field=models.ManyToManyField(related_name='Products', to='Products.Product'),
        ),
        migrations.AlterField(
            model_name='mainlist',
            name='LeftBarProduct',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Product'),
        ),
    ]
