# Generated by Django 2.2.6 on 2019-12-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20191207_0002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainList',
        ),
    ]
