# Generated by Django 2.2.6 on 2019-10-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20191023_2347'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='product',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='product',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='Products.Product'),
        ),
    ]
