# Generated by Django 2.2.6 on 2019-10-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_auto_20191024_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ManyToManyField(blank=True, default=None, to='Products.Product'),
        ),
    ]
