# Generated by Django 2.2.6 on 2019-10-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_auto_20191024_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(blank=True, choices=[('In Stock', 'В наличии'), ('Not Available', 'Нет в наличии')], default=None, max_length=24, null=True),
        ),
    ]
