# Generated by Django 2.2.6 on 2019-10-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_auto_20191024_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(blank=True, choices=[('В наличии', 'В наличии'), ('Нет в наличии', 'Нет в наличии')], default='В наличии', max_length=24, null=True),
        ),
    ]
