# Generated by Django 2.2.6 on 2019-10-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_auto_20191024_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not available', 'Not available')], default='Available', max_length=24, null=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
