# Generated by Django 2.2.6 on 2019-10-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_auto_20191024_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not available', 'Not available')], default='Available', max_length=24),
        ),
    ]
