# Generated by Django 2.2.6 on 2019-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_auto_20191024_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not available', 'Not available')], default='Available', max_length=24),
        ),
    ]
