# Generated by Django 2.2.6 on 2019-10-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20191024_1717'),
        ('Orders', '0010_auto_20191024_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='product',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Product'),
        ),
    ]
