# Generated by Django 2.2.6 on 2019-10-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_auto_20191024_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Verified', 'Verified'), ('Sent', 'Sent'), ('Completed', 'Completed')], default='New', max_length=24),
        ),
    ]
