# Generated by Django 2.2.6 on 2019-10-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0014_auto_20191024_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Product in order', 'verbose_name_plural': 'Products in order'},
        ),
    ]
