# Generated by Django 2.2.6 on 2019-12-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0021_auto_20191206_0514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Order status', 'verbose_name_plural': 'Order statuses'},
        ),
    ]
