# Generated by Django 2.2.6 on 2019-10-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20191023_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
