# Generated by Django 2.2.6 on 2019-11-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
