# Generated by Django 2.2.6 on 2019-11-30 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_productcategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.ProductCategory'),
        ),
    ]
