# Generated by Django 2.2.6 on 2019-11-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_productimage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='category',
        ),
    ]
