# Generated by Django 2.2.6 on 2019-12-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_auto_20191206_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainapp_botbar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='mainapp_leftbar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='mainapp_midbar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='mainapp_topbar',
            field=models.BooleanField(default=False),
        ),
    ]
