# Generated by Django 2.2.6 on 2019-12-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_auto_20191207_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='into_mainapp',
            field=models.BooleanField(default=False),
        ),
    ]
