# Generated by Django 2.2.6 on 2019-12-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_productimage_into_mainapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
