# Generated by Django 2.2.6 on 2019-12-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0021_product_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_specifiction',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
