# Generated by Django 2.2.9 on 2019-12-31 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_product_mini_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=32, verbose_name='Color')),
                ('image', models.ImageField(upload_to='colors/', verbose_name='Color image')),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
            },
        ),
        migrations.CreateModel(
            name='ProductShipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.BooleanField(default=False, verbose_name='Is it free shipping?')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product Shipping',
                'verbose_name_plural': 'Product Shippings',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Valuse')),
            ],
            options={
                'verbose_name': 'Rating Star',
                'verbose_name_plural': 'Rating Stars',
            },
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='into_mainapp',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='updated',
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.SlugField(default='', max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020, verbose_name='Release date'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='url',
            field=models.SlugField(default='', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.ProductCategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Shoppage description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Productpage description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_specifiction',
            field=models.TextField(blank=True, null=True, verbose_name='Specifiction'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is it active product?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is it new product?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainapp_botbar',
            field=models.BooleanField(default=False, verbose_name='Put this product on homepage botbar(max 8 product)?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainapp_leftbar',
            field=models.BooleanField(default=False, verbose_name='Put this product on homepage leftbar(max 1 product)?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainapp_midbar',
            field=models.BooleanField(default=False, verbose_name='Put this product on homepage midbar(max 3 product)?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainapp_topbar',
            field=models.BooleanField(default=False, verbose_name='Put this product on homepage topbar(max 8 product)?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mini_description',
            field=models.TextField(blank=True, null=True, verbose_name='Homepage description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is it main image?'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product', verbose_name='Product'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('text', models.TextField(max_length=4096, verbose_name='Text')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Reviews', verbose_name='Parent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16, verbose_name='IP adress')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product', verbose_name='Product')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.RatingStar', verbose_name='Star')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='Products.ProductColor', verbose_name='Product colors'),
        ),
        migrations.AddField(
            model_name='product',
            name='shippings',
            field=models.ManyToManyField(to='Products.ProductShipping', verbose_name='Product shippings'),
        ),
    ]
