# Generated by Django 2.2.9 on 2020-02-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_auto_20191231_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='text',
        ),
        migrations.AddField(
            model_name='reviews',
            name='cons',
            field=models.TextField(default='Null', max_length=4096, verbose_name='Cons'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='prons',
            field=models.TextField(default='Null', max_length=4096, verbose_name='Prons'),
        ),
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Value'),
        ),
    ]
