# Generated by Django 2.2.9 on 2020-02-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0025_auto_20200211_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='cons',
            field=models.TextField(max_length=4096, verbose_name='Cons'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='prons',
            field=models.TextField(max_length=4096, verbose_name='Prons'),
        ),
    ]
